[project]
name = "disenio-de-pruebas-control-de-calidad-y-mantenimiento-1-sin-6a"
version = "0.1.0"
description = "week4"
authors = [
    {name = "Erick Andrade",email = "aguilakrakatoa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "wily (>=1.25.0,<2.0.0)",
    "pytest (>=9.0.1,<10.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false